services:
  # Backend API
  - type: web
    name: pgpulse-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pgsql-db
          property: connectionString
      - key: PORT
        value: 8080
      - key: API_PORT
        value: 8080
      - key: API_HOST
        value: 0.0.0.0
      - key: ENV
        value: production
      - key: DATA_DIR
        value: /tmp/data
      - key: ARCHIVE_USERNAME
        value: archives
      - key: ARCHIVE_PASSWORD
        value: antispam
      - key: MAILING_LIST_EMAIL
        value: pgsql-hackers@postgresql.org

  # Frontend
  - type: web
    name: pgpulse-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile.frontend
    dockerContext: .
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: REACT_APP_API_URL
        value: https://pgpulse-backend.onrender.com

databases:
  - name: pgpulse-db
    databaseName: pgpulse
    plan: free
    region: oregon
